minijira/src/main/java/minijira/web/DatabaseBean.java
package minijira.web;

import ejb.database.model.*;
import ejb.database.DatabaseController;
import ejb.database.DatabaseControllerBean;


import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.util.List;

/**
 * Created by  Alexey Gorovoy
 * Date:    27.09.13
 * Time:    10:01
 * Email:   alexey.gorovoy.work@gmail.com
 */
@SuppressWarnings(value = "unchecked")
@ManagedBean
@SessionScoped
public class DatabaseBean {

    //@EJB
    DatabaseController dc;

    public DatabaseBean() {
        dc = new DatabaseControllerBean();
    }

    public List<Comment> getComments() {
        return dc.getComment();
    }

    public List<Comment> getCommentsByProject(int project_id) {
        return dc.getCommentByProject(project_id);
    }

    // Stored procedures
    public List<Comment> getCommentsByProjectSP(int project_id) {
        return dc.findCommentByProjectSP(project_id);
    }

    public List<Project> findProjectsByEmployeeSP(int employee_id) {
        return dc.findProjectByEmployeeSP(employee_id);
    }

    public List<Project> findProjectsByTechSP(int tech_id) {
        return dc.findProjectByTechSP(tech_id);
    }
    ///

    public List<Employee> getEmployees () {
        return (List<Employee>)dc.get(Employee.class);
    }

    public List<Tester> getTesters () {
        return (List<Tester>)dc.get(Tester.class);
    }

    public List<Manager> getManagers () {
        return (List<Manager>)dc.get(Manager.class);
    }

    public List<CustomerAgent> getCustomerAgents () {
        return (List<CustomerAgent>)dc.get(CustomerAgent.class);
    }

    public List<Developer> getDevelopers () {
        return (List<Developer>)dc.get(Developer.class);
    }

    public List<Office> getOffices () {
        return (List<Office>)dc.get(Office.class);
    }

    public List<Priority> getPriorities() {
        return (List<Priority>)dc.get(Priority.class);
    }

    public List<Workflow> getWorkflows() {
        return (List<Workflow>)dc.get(Workflow.class);
    }

    public List<Rank> getRanks() {
        return (List<Rank>)dc.get(Rank.class);
    }

    public List<ProjectType> getProjectTypes() {
        return (List<ProjectType>)dc.get(ProjectType.class);
    }

    public List<TestType> getTestTypes() {
        return (List<TestType>)dc.get(TestType.class);
    }

    public List<ManagerType> getManagerTypes() {
        return (List<ManagerType>)dc.get(ManagerType.class);
    }

    public List<Tech> getTechs() {
        return (List<Tech>)dc.get(Tech.class);
    }

    public List<Customer> getCustomers() {
        return (List<Customer>)dc.get(Customer.class);
    }

    public List<Project> getProjects() {
        return (List<Project>)dc.get(Project.class);
    }

    public List<Task> getTasks() {
        return (List<Task>)dc.get(Task.class);
    }
}

minijira/src/main/webapp/secure/edit_project.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
        >
<h:body>

    <ui:composition template="/blocks/dafaultPage.xhtml">

        <ui:define name="content">
            <h3>Edit project</h3>

            <h:form styleClass="form-actions">
                <h:outputLabel value="Title">
                    <h:inputText value="#{projectEditor.project.title}" />
                </h:outputLabel>
                <br/>
                <h:outputLabel value="Type">
                    <h:selectOneMenu value="#{projectEditor.projectTypeId}">
                        <f:selectItems value="#{databaseBean.projectTypes}" var="t"
                                       itemLabel="#{t.title}" itemValue="#{t.id}" />
                    </h:selectOneMenu>
                </h:outputLabel>
                <br/>
                <h:outputLabel value="Description">
                    <h:inputText value="#{projectEditor.project.title}" />
                </h:outputLabel>
                <h:commandButton value="Save!" action="#{projectEditor.save()}" styleClass="btn btn-danger"/>
            </h:form>

        </ui:define>

    </ui:composition>

</h:body>

</html>